export const climateDigitalMap = new Map([
	["Hallway[Enable]", 501],
    ["Hall[Enable]", 502],
    ["Livingroom[Enable]", 503],
    ["Kitchen[Enable]", 504],
    ["Bathroom[Enable]", 505],
    ["Bedroom[Enable]", 506],
    ["Kids_room[Enable]", 507],
    ["2nd_floor_Bathrooms[Enable]", 508],
    ["2nd_floor_stairs[Enable]", 510],
    ["Cabinet[Enable]", 511],
    ["3rd_floor_stairs[Enable]", 512],
    ["3rd_floor_Bathroom[Enable]", 513],
    ["Workshop[Enable]", 514],
    ["Garage[Enable]", 515],
    ["Boiler[Enable]", 516],
    ["Technical_room[Enable]", 517],
    ["Livingroom[Enable]", 518],
    ["Kitchen[Enable]", 520],
    ["Bedroom[Enable]", 521],
    ["Kids_room[Enable]", 522],
    ["2nd_floor_stairs[Enable]", 523],
    ["Cabinet[Enable]", 524],
    ["3rd_floor_stairs[Enable]", 525],
    ["Workshop[Enable]", 526],
])

export const ClimateFeedbackDigitalMap = new Map([
	[601, "Hallway[Is_On]"],
]);